# Generated by Django 6.1.1 on 2026-10-01 21:41

import django.core.files.storage
import django.db.models.deletion
import employer_portal.models
import pathlib
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_company', models.CharField(max_length=200)),
                ('requester_job_title', models.CharField(blank=True, max_length=150)),
                ('requester_phone', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField(help_text='Why the requester needs access to the private material.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_employer_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('academic', 'Academic Certificate'), ('professional', 'Professional Certificate'), ('supporting', 'Supporting Document'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('D:/Dennis-Portfolio/private/documents')), upload_to=employer_portal.models.private_document_upload_path)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', '-uploaded_at'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='employer_po_documen_f00c43_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='Whether this particular document is approved for access.')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='employer_portal.accessrequest')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_request_items', to='employer_portal.document')),
            ],
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_documents',
            field=models.ManyToManyField(blank=True, related_name='access_requests', through='employer_portal.DocumentAccessRequest', to='employer_portal.document'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company_website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Mark the employer identity as verified after review.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='employer_po_email_5c4bd9_idx'), models.Index(fields=['company_name'], name='employer_po_company_b46e9d_idx')],
            },
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='employer_portal.employer'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('request_submitted', 'Access Request Submitted'), ('request_approved', 'Access Request Approved'), ('request_rejected', 'Access Request Rejected'), ('portal_viewed', 'Employer Portal Viewed'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('referee_viewed', 'Referee Details Viewed'), ('contact_submitted', 'Contact Form Submitted'), ('access_revoked', 'Access Revoked')], max_length=40)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_identifier', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='employer_portal.accessrequest')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='employer_portal.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('organisation', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('relationship', models.CharField(blank=True, help_text='For example: Former Line Manager or Operations Director.', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='employer_po_is_acti_4ff284_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefereeAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='Whether this referee may be shown to the employer.')),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_requests', to='employer_portal.accessrequest')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_request_items', to='employer_portal.referee')),
            ],
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_referees',
            field=models.ManyToManyField(blank=True, related_name='access_requests', through='employer_portal.RefereeAccessRequest', to='employer_portal.referee'),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('access_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant', to='employer_portal.accessrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='employer_po_token_71e257_idx'), models.Index(fields=['expires_at'], name='employer_po_expires_bd14c4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentaccessrequest',
            index=models.Index(fields=['access_request', 'approved'], name='employer_po_access__5170b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentaccessrequest',
            constraint=models.UniqueConstraint(fields=('access_request', 'document'), name='unique_request_document'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['event_type', 'created_at'], name='employer_po_event_t_100b67_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['employer', 'created_at'], name='employer_po_employe_8f37c7_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['access_request', 'created_at'], name='employer_po_access__8333a9_idx'),
        ),
        migrations.AddIndex(
            model_name='refereeaccessrequest',
            index=models.Index(fields=['access_request', 'approved'], name='employer_po_access__e55a2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='refereeaccessrequest',
            constraint=models.UniqueConstraint(fields=('access_request', 'referee'), name='unique_request_referee'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', 'created_at'], name='employer_po_status_858028_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['requester_email'], name='employer_po_request_029d17_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['request_id'], name='employer_po_request_4821ce_idx'),
        ),
    ]
