# Generated by Django 6.1.1 on 2026-10-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='grant_expires_after_start'),
        ),
    ]
