# Generated by Django 6.1.1 on 2026-10-02 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_portal', '0002_accessgrant_grant_expires_after_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['is_active', 'expires_at'], name='employer_po_is_acti_1fe12c_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['resource_type', 'created_at'], name='employer_po_resourc_952b69_idx'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', 'expires_at'], name='employer_po_status_ea86c8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active', 'updated_at'], name='employer_po_is_acti_2604c6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccessrequest',
            index=models.Index(fields=['document', 'approved'], name='employer_po_documen_8cf2da_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['is_active', 'created_at'], name='employer_po_is_acti_6612f3_idx'),
        ),
        migrations.AddIndex(
            model_name='referee',
            index=models.Index(fields=['organisation', 'is_active'], name='employer_po_organis_958e16_idx'),
        ),
        migrations.AddIndex(
            model_name='refereeaccessrequest',
            index=models.Index(fields=['referee', 'approved'], name='employer_po_referee_0a0a7c_idx'),
        ),
    ]
