# Generated by Django 6.1.1 on 2026-10-03 21:28

import employer_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_portal', '0003_accessgrant_employer_po_is_acti_1fe12c_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessgrant',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='accesslog',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'get_latest_by': 'uploaded_at', 'ordering': ['document_type', '-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'employer', 'verbose_name_plural': 'employers'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'get_latest_by': 'created_at', 'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='accessgrant',
            new_name='grant_token_active_idx',
            old_name='employer_po_token_71e257_idx',
        ),
        migrations.RenameIndex(
            model_name='accessgrant',
            new_name='grant_active_expires_idx',
            old_name='employer_po_is_acti_1fe12c_idx',
        ),
        migrations.RenameIndex(
            model_name='accessgrant',
            new_name='grant_expires_idx',
            old_name='employer_po_expires_bd14c4_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='log_event_created_idx',
            old_name='employer_po_event_t_100b67_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='log_employer_created_idx',
            old_name='employer_po_employe_8f37c7_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='log_request_created_idx',
            old_name='employer_po_access__8333a9_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='log_res_created_idx',
            old_name='employer_po_resourc_952b69_idx',
        ),
        migrations.RenameIndex(
            model_name='accessrequest',
            new_name='ar_status_created_idx',
            old_name='employer_po_status_858028_idx',
        ),
        migrations.RenameIndex(
            model_name='accessrequest',
            new_name='ar_status_expires_idx',
            old_name='employer_po_status_ea86c8_idx',
        ),
        migrations.RenameIndex(
            model_name='accessrequest',
            new_name='ar_email_idx',
            old_name='employer_po_request_029d17_idx',
        ),
        migrations.RenameIndex(
            model_name='accessrequest',
            new_name='ar_request_id_idx',
            old_name='employer_po_request_4821ce_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='doc_type_active_idx',
            old_name='employer_po_documen_f00c43_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='doc_active_updated_idx',
            old_name='employer_po_is_acti_2604c6_idx',
        ),
        migrations.RenameIndex(
            model_name='documentaccessrequest',
            new_name='dar_req_approved_idx',
            old_name='employer_po_access__5170b5_idx',
        ),
        migrations.RenameIndex(
            model_name='documentaccessrequest',
            new_name='dar_doc_approved_idx',
            old_name='employer_po_documen_8cf2da_idx',
        ),
        migrations.RenameIndex(
            model_name='employer',
            new_name='employer_email_idx',
            old_name='employer_po_email_5c4bd9_idx',
        ),
        migrations.RenameIndex(
            model_name='employer',
            new_name='employer_company_idx',
            old_name='employer_po_company_b46e9d_idx',
        ),
        migrations.RenameIndex(
            model_name='employer',
            new_name='employer_active_created_idx',
            old_name='employer_po_is_acti_6612f3_idx',
        ),
        migrations.RenameIndex(
            model_name='referee',
            new_name='referee_active_idx',
            old_name='employer_po_is_acti_4ff284_idx',
        ),
        migrations.RenameIndex(
            model_name='referee',
            new_name='referee_org_active_idx',
            old_name='employer_po_organis_958e16_idx',
        ),
        migrations.RenameIndex(
            model_name='refereeaccessrequest',
            new_name='rar_req_approved_idx',
            old_name='employer_po_access__e55a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='refereeaccessrequest',
            new_name='rar_ref_approved_idx',
            old_name='employer_po_referee_0a0a7c_idx',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='event_type',
            field=models.CharField(choices=[('request_submitted', 'Access Request Submitted'), ('request_approved', 'Access Request Approved'), ('request_rejected', 'Access Request Rejected'), ('request_expired', 'Access Request Expired'), ('portal_viewed', 'Employer Portal Viewed'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('referee_viewed', 'Referee Details Viewed'), ('contact_submitted', 'Contact Form Submitted'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('access_expired', 'Access Expired'), ('login', 'Staff Login'), ('logout', 'Staff Logout')], max_length=40),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, storage=employer_portal.models.PrivateDocumentStorage(), upload_to=employer_portal.models.private_document_upload_path),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['revoked_at', 'expires_at'], name='grant_revoked_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['is_verified', 'is_active'], name='employer_verified_active_idx'),
        ),
    ]
