# Generated by Django 6.1.1 on 2026-10-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_portal', '0004_alter_accessgrant_options_alter_accesslog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessgrant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['document_type', '-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-created_at'], 'verbose_name': 'employer', 'verbose_name_plural': 'employers'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='event_type',
            field=models.CharField(choices=[('request_submitted', 'Access Request Submitted'), ('request_approved', 'Access Request Approved'), ('request_rejected', 'Access Request Rejected'), ('request_expired', 'Access Request Expired'), ('request_reopened', 'Access Request Reopened'), ('portal_viewed', 'Employer Portal Viewed'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('referee_viewed', 'Referee Details Viewed'), ('contact_submitted', 'Contact Form Submitted'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('access_expired', 'Access Expired'), ('login', 'Staff Login'), ('logout', 'Staff Logout')], max_length=40),
        ),
        migrations.AlterField(
            model_name='documentaccessrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referee',
            name='relationship',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='refereeaccessrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
