# Generated by Django 6.1.1 on 2026-10-08 16:46

import employer_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_portal', '0005_alter_accessgrant_options_alter_accesslog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, storage=employer_portal.models.PrivateDocumentStorage(), upload_to=employer_portal.models.private_document_upload_path, validators=[employer_portal.models.validate_document_file]),
        ),
    ]
